[features]
seeds = false
skip-lint = false
[programs.localnet]
contracts = "AnWA7pY1LvXqorCTmZHTA2trn71XG1JWLF1WkAXh7oWU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/simon/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
